const imagekit = require("../config/imagekit");
const Report = require("../models/Report");
const pdfParse = require("pdf-parse");
const mammoth = require("mammoth");
const { GoogleGenAI } = require("@google/genai");

exports.uploadReport = async (req, res) => {
    console.log("[Upload] Received upload request");
    try {
        const file = req.file;
        if (!file) {
            console.error("[Upload] No file provided in request");
            return res.status(400).json({ error: "No file provided" });
        }

        let aiSummary = "";
        const apiKey = process.env.GEMINI_API_KEY;

        console.log(`[Upload] File: ${file.originalname}, Mimetype: ${file.mimetype}, Size: ${file.size} bytes`);

        if (apiKey) {
            try {
                const ai = new GoogleGenAI({ apiKey: apiKey });
                let textContent = "";
                let imagePart = null;

                const isPdf = file.mimetype === "application/pdf" || file.originalname.toLowerCase().endsWith(".pdf");
                const isWord = file.mimetype === "application/vnd.openxmlformats-officedocument.wordprocessingml.document" || file.originalname.toLowerCase().endsWith(".docx");
                const isImage = file.mimetype.startsWith("image/");

                if (isPdf) {
                    console.log("[AI] Parsing PDF text...");
                    const pdfData = await pdfParse(file.buffer);
                    textContent = pdfData.text || "";
                } else if (isWord) {
                    console.log("[AI] Parsing Word document text...");
                    const result = await mammoth.extractRawText({ buffer: file.buffer });
                    textContent = result.value || "";
                } else if (isImage) {
                    console.log("[AI] Preparing image for multimodal analysis...");
                    imagePart = {
                        inline_data: {
                            mime_type: file.mimetype,
                            data: file.buffer.toString("base64")
                        }
                    };
                }

                if (textContent.trim().length > 2 || imagePart) {
                    console.log("[AI] Calling Gemini API (gemini-2.5-flash)...");
                    let result;
                    try {
                        result = await ai.models.generateContent({
                            model: "gemini-2.5-flash",
                            contents: [{ role: "user", parts: [
                                { text: "Please analyze and summarize this medical document. Use professional Markdown formatting. Use **bold** for key findings, abnormal values, and critical terms. Use bullet points for clarity. Structure the summary with headers like 'Key Findings', 'Analysis', and 'Recommendations'. Make it look like a professional clinical summary." },
                                ...(textContent ? [{ text: `Content:\n${textContent}` }] : []),
                                ...(imagePart ? [imagePart] : [])
                            ] }],
                        });
                    } catch (modelError) {
                        console.error("[AI] Primary model failed, trying fallback...", modelError.message);
                        result = await ai.models.generateContent({
                            model: "gemini-2.0-flash",
                            contents: [{ role: "user", parts: [
                                { text: "Summarize this medical report briefly. Use **bold** for important values." },
                                ...(textContent ? [{ text: textContent }] : []),
                                ...(imagePart ? [imagePart] : [])
                            ] }],
                        });
                    }
                    
                    aiSummary = result.text || "";
                    if (!aiSummary && result.candidates?.[0]?.content?.parts?.[0]?.text) {
                        aiSummary = result.candidates[0].content.parts[0].text;
                    }

                    if (!aiSummary) {
                        aiSummary = "AI Summary: Document processed but no summary text was generated by the AI.";
                    }
                    console.log("[AI] Summary generated successfully!");
                } else {
                    aiSummary = "AI Summary: The document appears to be empty or contains no readable text/images.";
                }
            } catch (summaryError) {
                console.error("[AI] Process failed:", summaryError.message);
                aiSummary = `AI Summary Error: ${summaryError.message}`;
            }
        } else {
            aiSummary = "AI Summary: Missing GEMINI_API_KEY in server configuration.";
        }

        // Upload file to ImageKit
        console.log("[ImageKit] Uploading file...");
        const uploadFile = await imagekit.upload({
            file: file.buffer,
            fileName: file.originalname,
        });

        const folderId = (req.body.folderId && req.body.folderId !== "null" && req.body.folderId !== "") ? req.body.folderId : null;

        const report = new Report({
            user: req.user._id,
            title: req.body.title || file.originalname,
            fileUrl: uploadFile.url,
            folder: folderId,
            summary: aiSummary,
        });

        await report.save();
        console.log("[Upload] Finalized with summary length:", aiSummary.length);

        res.json({ message: "Report uploaded successfully", report });
    } catch (error) {
        console.error("[Upload] Critical:", error.message);
        res.status(500).json({ error: error.message });
    }
};

exports.getMyReports = async (req, res) => {
    try {
        const reports = await Report.find({ user: req.user._id }).sort({ createdAt: -1 });
        res.json(reports);
    } catch (error) {
        res.status(500).json({ error: error.message });
    }
};

exports.getReportById = async (req, res) => {
    try {
        const report = await Report.findOne({ _id: req.params.id, user: req.user._id });
        if (!report) return res.status(404).json({ message: "Report not found" });
        res.json({ report });
    } catch (error) {
        res.status(500).json({ error: error.message });
    }
};

exports.deleteReport = async (req, res) => {
    try {
        const report = await Report.findOne({ _id: req.params.id, user: req.user._id });
        if (!report) return res.status(404).json({ message: "Report not found" });
        await Report.deleteOne({ _id: req.params.id });
        res.json({ message: "Report deleted successfully" });
    } catch (error) {
        res.status(500).json({ error: error.message });
    }
};

exports.updateReport = async (req, res) => {
    try {
        const { title } = req.body;
        if (!title) return res.status(400).json({ error: "Title is required" });

        const report = await Report.findOneAndUpdate(
            { _id: req.params.id, user: req.user._id },
            { title },
            { new: true }
        );

        if (!report) return res.status(404).json({ message: "Report not found" });

        res.json({ message: "Report updated successfully", report });
    } catch (error) {
        console.error("[Update] Critical:", error.message);
        res.status(500).json({ error: error.message });
    }
};
